/* ============ S1L Strategien je Event — GEMEINSAME QUELLE ============
   Einmal HIER pflegen -> Baukasten (S1L-R4-Raid.html) UND Timeline (S1L-R4-Templates.html)
   nutzen exakt dieselben Strategien. Auswahl-Labels (tags) je Sprache als {de,en,tr,ru}.
   Die GEWAEHLTE Strategie je Event wird live ueber Firebase-Collection 'stratchoice' geteilt.
   Pflege: Alex. Einbinden: <script src="strat.js"></script> VOR dem Seiten-Skript. */
var STRAT={
  duell:[ { id:"duell-tag1", prio:false, tags:{de:["Tag 1 - Radar","Fetzen","Spionage"],en:["Day 1 - Radar","Scraps","Spy"],tr:["1. Gün - Radar","Scraps","Casus"],ru:["День 1 - Radar","Scraps","Шпион"]},
    de:"TAG 1 RADAR: Fokus = Ausruestungsfetzen verwenden (im Golden Window mit Power-Play Ausruestungsaufwertung dreifach), Spionagemissionen (kosten Ausdauer), Ressourcen sammeln. AUFHEBEN: Bau-Speedups fuer Tag 2; Forschungs-Speedups + Behemoth Cells + Behemoth Serum fuer Tag 3. Genaue Golden-Window-Zeit im Hub/Chat.",
    en:"DAY 1 RADAR: focus = use gear scraps (triple in the Golden Window with Power Play Gear Enhancement), spy missions (cost stamina), gather resources. SAVE: build speedups for Day 2; research speedups + Behemoth Cells + Behemoth Serum for Day 3. Exact Golden Window time in hub/chat.",
    tr:"1. GUN RADAR: odak = gear scraps kullan (Power Play Gear Enhancement ile Golden Window'da uc kat), casus gorevleri (dayaniklilik harcar), kaynak topla. SAKLA: build speedups 2. gun icin; research speedups + Behemoth Cells + Behemoth Serum 3. gun icin. Tam Golden Window saati hub/chat'te.",
    ru:"ДЕНЬ 1 RADAR: фокус = использовать gear scraps (в Golden Window с Power Play Gear Enhancement втрое), spy-миссии (тратят выносливость), собирать ресурсы. КОПИ: build speedups на День 2; research speedups + Behemoth Cells + Behemoth Serum на День 3. Точное время Golden Window в хабе/чате." },
  { id:"duell-tag2", prio:false, tags:{de:["Tag 2 - Basisbau","Bau-Speedups","Golden Window"],en:["Day 2 - Base Building","Build speedups","Golden Window"],tr:["2. Gün - Base Building","Build speedups","Golden Window"],ru:["День 2 - Base Building","Build speedups","Golden Window"]},
    de:"TAG 2 BASISBAU: Fokus = BAUEN. Bau-Speedups im Golden Window (mit Power-Play Siedlungsbau) dreifach -> hier dumpen, vorher NICHT einzeln verbrauchen. S-Stufe (+75.000) und LKW (+50.000) als Extra. AUFHEBEN: Forschungs-Speedups + Behemoth Cells + Behemoth Serum + Kampfmedaillen fuer Tag 3; Heldenfragmente + Rekrutierungsmarken fuer Tag 4.",
    en:"DAY 2 BASE BUILDING: focus = BUILDING. Build speedups triple in the Golden Window (with Power Play Settlement Building) -> dump here, do NOT spend them one by one before. S-tier (+75,000) and truck (+50,000) as extras. SAVE: research speedups + Behemoth Cells + Behemoth Serum + Battle Medals for Day 3; hero fragments + recruit tokens for Day 4.",
    tr:"2. GUN BASE BUILDING: odak = INSAAT. Build speedups Golden Window'da (Power Play Settlement Building ile) uc kat -> burada harca, oncesinde tek tek HARCAMA. S-tier (+75.000) ve truck (+50.000) ekstra. SAKLA: research speedups + Behemoth Cells + Behemoth Serum + Battle Medal 3. gun icin; hero parcalari + rekrutasyon marka 4. gun icin.",
    ru:"ДЕНЬ 2 BASE BUILDING: фокус = СТРОЙКА. Build speedups втрое в Golden Window (с Power Play Settlement Building) -> сливай здесь, НЕ трать по одному заранее. S-tier (+75.000) и грузовик (+50.000) как бонус. КОПИ: research speedups + Behemoth Cells + Behemoth Serum + Battle Medals на День 3; фрагменты героев + жетоны вербовки на День 4." },
  { id:"duell-tag3", prio:false, tags:{de:["Tag 3 - Technologie","Forschungs-Speedups","Behemoth"],en:["Day 3 - Technology","Research speedups","Behemoth"],tr:["3. Gün - Technology","Research speedups","Behemoth"],ru:["День 3 - Technology","Research speedups","Behemoth"]},
    de:"TAG 3 TECHNOLOGIE: Fokus = Forschungs-Speedups im Golden Window (mit Power-Play Technologieforschung) dreifach. Dazu Behemoth Cells (+12.000), Spionagemission (+30.000), Kampfmedaille ausgeben (+2.500). AUFHEBEN: Heldenfragmente + Rekrutierungsmarken fuer Tag 4; Spionage + Ressourcen fuers Truppen-Training fuer Tag 5.",
    en:"DAY 3 TECHNOLOGY: focus = research speedups triple in the Golden Window (with Power Play Technology Research). Plus Behemoth Cells (+12,000), spy mission (+30,000), spend Battle Medal (+2,500). SAVE: hero fragments + recruit tokens for Day 4; spy + resources for troop training for Day 5.",
    tr:"3. GUN TECHNOLOGY: odak = research speedups Golden Window'da (Power Play Technology Research ile) uc kat. Ayrica Behemoth Cells (+12.000), casus gorevi (+30.000), Battle Medal harca (+2.500). SAKLA: hero parcalari + rekrutasyon marka 4. gun icin; casus + birlik egitimi icin kaynaklar 5. gun icin.",
    ru:"ДЕНЬ 3 TECHNOLOGY: фокус = research speedups втрое в Golden Window (с Power Play Technology Research). Плюс Behemoth Cells (+12.000), spy-миссия (+30.000), потратить Battle Medal (+2.500). КОПИ: фрагменты героев + жетоны вербовки на День 4; spy + ресурсы для тренировки войск на День 5." },
  { id:"duell-tag4", prio:true, tags:{de:["Tag 4 - Helden","Fragmente","Alpha-Bestie"],en:["Day 4 - Heroes","Fragments","Alpha Beast"],tr:["4. Gün - Heroes","Parçalar","Alpha Beast"],ru:["День 4 - Heroes","Фрагменты","Alpha Beast"]},
    de:"TAG 4 HELDEN: Heldenfragmente einsetzen + Rekrutierungen - legendaere Fragmente und Wunsch-Rekrutierung am staerksten (Boost je Spieler anders). Fragmente farmen: Rallys auf die MITTLEREN Monster (Alpha-Bestie); normale und fette Infizierte geben keine. Ausdauer nutzen (regeneriert + VIP-/Edelstein-Laden), Rest fuer Tag 5 (Spionagemissionen) behalten.",
    en:"DAY 4 HEROES: use hero fragments + recruitments - legendary fragments and wish recruitment are strongest (boosts differ per player). Farm fragments: rallies vs the MEDIUM monsters (Alpha Beast); normal and fat infected give none. Use stamina (regens + VIP/Gem shop), keep a reserve for Day 5 (spy missions).",
    tr:"4. GUN HEROES: kahraman parcalari kullan + rekrutasyonlar - efsanevi parcalar ve istek rekrutasyonu en guclu (boost oyuncuya gore degisir). Parca farmla: ORTA canavarlara (Alpha-Bestie) rally; normal ve sisman enfekteler vermez. Dayaniklilik kullan (yenilenir + VIP/Gem magaza), 5. gun (spy gorevleri) icin rezerv birak.",
    ru:"ДЕНЬ 4 HEROES: используй фрагменты героев + вербовки - легендарные фрагменты и желаемая вербовка сильнее всего (бусты у каждого разные). Фарм фрагментов: rally на СРЕДНИХ монстров (Alpha-Bestie); обычные и толстые заражённые не дают. Выносливость трать (восстанавливается + VIP/Gem магазин), оставь резерв на День 5 (spy-миссии)." },
  { id:"duell-tag5", prio:false, tags:{de:["Tag 5 - Schlachtvorbereitung","Spionage","Training"],en:["Day 5 - Battle Prep","Spy","Training"],tr:["5. Gün - Battle Prep","Casus","Eğitim"],ru:["День 5 - Battle Prep","Шпион","Тренировка"]},
    de:"TAG 5 SCHLACHTVORBEREITUNG: KEIN Golden Window (keine Power-Play-Truppen-Runde). Fokus = Spionagemission (+37.500) + Truppen trainieren (hoehere Stufen mehr Punkte; Truppen hat man genug, aber Training braucht RESSOURCEN -> genug bereithalten). AUFHEBEN: Friedenskuppeln + alle Beschleuniger fuer Tag 6; Ausruestungsfetzen + Spionage + Kommandantenausdauer fuer Montag (Tag 1, +3 Tage - Sonntag ist duellfrei).",
    en:"DAY 5 BATTLE PREP: NO Golden Window (no Power Play troop round). Focus = spy mission (+37,500) + train troops (higher tiers more points; you have enough troops, but training needs RESOURCES -> keep enough ready). SAVE: Peace Shields + all speedups for Day 6; gear scraps + spy + commander stamina for Monday (Day 1, +3 days - Sunday has no duel).",
    tr:"5. GUN BATTLE PREP: Golden Window YOK (Power Play birlik turu yok). Odak = casus gorevi (+37.500) + birlik egit (ust seviyeler daha cok puan; birlik yeterli ama egitim KAYNAK ister -> yeterince hazir tut). SAKLA: Peace Shields + tum speedups 6. gun icin; gear scraps + casus + komutan dayanikligi Pazartesi icin (1. gun, +3 gun - Pazar duel yok).",
    ru:"ДЕНЬ 5 BATTLE PREP: НЕТ Golden Window (нет раунда войск в Power Play). Фокус = spy-миссия (+37.500) + тренировать войска (выше уровень - больше очков; войск хватает, но тренировка требует РЕСУРСОВ -> держи запас). КОПИ: Peace Shields + все speedups на День 6; gear scraps + spy + выносливость командира на понедельник (День 1, +3 дня - в воскресенье дуэли нет)." },
  { id:"duell-tag6-kuppel", prio:true, tags:{de:["Tag 6 - Alle unter die Kuppel","Verteidigen","Verstaerken"],en:["Day 6 - Everyone under the dome","Defend","Reinforce"],tr:["6. Gun - Herkes dome altina","Savun","Takviye"],ru:["День 6 - Все под купол","Защита","Усиление"]},
    de:"TAG 6 ALLE UNTER DIE KUPPEL: Bitte alle unter die Kuppel - darunter kann euch niemand angreifen. Wer angreift oder kaempft, verliert die Kuppel und muss 30 Min warten. Sammeln geht, aber Trupps DRAUSSEN sind angreifbar - spaetestens bei Angriffen zurueckrufen. Siedlungen lassen sich mit bis zu 5 Plaetzen verstaerken. Angreifer treffen IMMER zuerst den staerksten Verstaerker; gewinnt er und schuetzt die Siedlung, zaehlt der Kill fuer UNS. Darum Siedlungen OHNE Kuppel mit der STAERKSTEN Truppe verstaerken - schwaechere Angreifer unterschaetzen die Verteidigung. Chat beobachten und VOR jedem Angriff fragen, damit wir uns abstimmen. Strategie kann sich jederzeit aendern.",
    en:"DAY 6 EVERYONE UNDER THE DOME: please all go under the dome - there no one can attack you. Whoever attacks or fights loses the dome and must wait 30 min. Gathering is fine, but troops OUTSIDE can be attacked - recall them at the latest when attacks come. Settlements can be reinforced with up to 5 slots. Attackers ALWAYS hit the strongest reinforcer first; if they win and protect the settlement, the kill counts for US. So reinforce settlements WITHOUT a dome with your STRONGEST troops - weaker attackers underestimate the defense. Watch the chat and ASK before every attack so we coordinate. Strategy can change at any time.",
    tr:"6. GUN HERKES DOME ALTINA: lutfen herkes dome altina gecsin - orada kimse size saldiramaz. Saldiran veya savasan dome'u kaybeder ve 30 dk bekler. Toplama serbest, ama DISARIDAKI birlikler saldirilabilir - saldirilar gelince en gec geri cagirin. Yerlesimler 5 yere kadar takviye edilebilir. Saldiranlar HER ZAMAN once en guclu takviyeciye vurur; kazanip yerlesimi korursa kill BIZE sayilir. O yuzden dome'suz yerlesimleri EN GUCLU birlikle takviye edin - zayif saldiranlar savunmayi hafife alir. Chat'i izleyin ve her saldiridan ONCE sorun, uyum saglayalim. Strateji her an degisebilir.",
    ru:"ДЕНЬ 6 ВСЕ ПОД КУПОЛ: пожалуйста, все под купол - там вас никто не атакует. Кто атакует или воюет, теряет купол и ждёт 30 мин. Сбор можно, но войска СНАРУЖИ можно атаковать - отзывайте их самое позднее при атаках. Поселения усиливаются до 5 мест. Атакующие ВСЕГДА сначала бьют сильнейшего усилителя; если он побеждает и защищает поселение, килл засчитывается НАМ. Поэтому поселения БЕЗ купола усиливайте САМЫМИ сильными войсками - слабые атакующие недооценивают оборону. Следите за чатом и спрашивайте ПЕРЕД каждой атакой, чтобы согласовать. Стратегия может измениться в любой момент." },
  { id:"duell-tag6-v1", prio:false, tags:{de:["Tag 6 V1 (?)","Rotation","Kuppel"],en:["Day 6 V1 (?)","Rotation","Dome"],tr:["6. Gün V1 (?)","Rotasyon","Dome"],ru:["День 6 V1 (?)","Ротация","Купол"]},
    de:"TAG 6 V1 (in Abstimmung) - Rotation: Vorm Schlafen Kuppel AN. Feste 6er-Teams: immer 1 greift OHNE Kuppel am Feind-Stützpunkt an, die anderen 5 verstärken/verteidigen. Bei Gegenschaden zurück, dann rotieren (Nächster ohne Kuppel, Voriger zieht die Kuppel wieder hoch - 30 Min Abklingzeit). Offline? Truppen verfügbar lassen. Gegner über 3 Stufen unter dir = KEINE Punkte.",
    en:"DAY 6 V1 (under discussion) - Rotation: dome ON before sleeping. Fixed teams of 6: always 1 attacks WITHOUT dome at the enemy base, the other 5 reinforce/defend. On counter-damage retreat, then rotate (next without dome, previous raises the dome again - 30 min cooldown). Offline? Leave troops available. Enemies more than 3 levels below you = NO points.",
    tr:"6. GÜN V1 (görüşülüyor) - Rotasyon: yatmadan önce dome AÇIK. Sabit 6'lı takımlar: her zaman 1 düşman üssünde dome OLMADAN saldırır, diğer 5 takviye/savunma yapar. Karşı hasarda geri, sonra rotasyon (sıradaki dome'suz, önceki dome'u tekrar açar - 30 dk bekleme). Offline? Birlikleri hazır bırak. Senden 3 seviyeden fazla düşük düşmanlar = PUAN YOK.",
    ru:"ДЕНЬ 6 V1 (обсуждается) - Ротация: купол ВКЛ перед сном. Фиксированные группы по 6: всегда 1 атакует БЕЗ купола на базе врага, остальные 5 усиливают/защищают. При ответном уроне назад, затем ротация (следующий без купола, предыдущий снова поднимает купол - 30 мин перезарядка). Офлайн? Оставь войска доступными. Враги более чем на 3 уровня ниже = НЕТ очков." },
  { id:"duell-tag6-v2", prio:false, tags:{de:["Tag 6 V2 (?)","Dauerverteidiger","Kuppel"],en:["Day 6 V2 (?)","Permanent defender","Dome"],tr:["6. Gün V2 (?)","Kalıcı savunucu","Dome"],ru:["День 6 V2 (?)","Защитник","Купол"]},
    de:"TAG 6 V2 (in Abstimmung) - Dauerverteidiger: Ein eh-online Spieler bleibt GANZ OHNE Kuppel, voll verstärkt, und verteidigt am Stützpunkt jeden ankommenden Fremden; bei Gefahr sofort Kuppel an (Abklingzeit längst vorbei). Mit Kuppel: nicht angreifbar, aber auch nicht angreifend. Starke schicken dem Verteidiger Truppen + beobachten die Statistik (rechtzeitig fliehen, mit Versetzer verstecken).",
    en:"DAY 6 V2 (under discussion) - Permanent defender: a player who's online anyway stays WITHOUT a dome, fully reinforced, and defends every incoming enemy at the base; on danger turn the dome on instantly (cooldown long over). With dome: not attackable but also can't attack. The strong send the defender troops + watch the stats (flee in time, hide with a teleporter).",
    tr:"6. GÜN V2 (görüşülüyor) - Kalıcı savunucu: zaten online olan bir oyuncu DOME'SUZ kalır, tam takviyeli, ve üste gelen her düşmanı savunur; tehlikede dome'u anında açar (bekleme çoktan bitti). Dome ile: saldırılamaz ama saldıramaz da. Güçlüler savunucuya birlik gönderir + istatistiği izler (zamanında kaç, ışınlayıcıyla saklan).",
    ru:"ДЕНЬ 6 V2 (обсуждается) - Постоянный защитник: игрок, который и так онлайн, остаётся БЕЗ купола, полностью усилен, и защищает на базе каждого входящего врага; при опасности сразу включает купол (перезарядка давно прошла). С куполом: неуязвим, но и не атакует. Сильные шлют защитнику войска + следят за статистикой (вовремя бежать, прятаться телепортом)." } ],
  loewe:[ { id:"loewe-selbst", prio:true, tags:{de:["Boss","Schaden"],en:["Boss","Damage"],tr:["Boss","Hasar"],ru:["Босс","Урон"]},
    de:"Selbst-Rally: Wer rally-faehig ist, startet am besten eine eigene Rally (kein Limit) - kuerzeste Vorlaufzeit = mehr Schlaege/Min. Am besten auf Boss-Schaden-Helden + Signature Weapons umruesten, Buffs in diesen 30 Min einsetzen.",
    en:"Self-rally: if you can rally, best to start your own (no limit) - shortest lead time = more hits/min. Best to switch to single-target heroes + signature weapons, use buffs in these 30 min.",
    tr:"Kendi rally'in: Rally başlatabilen en iyisi kendi rally'sini başlatsın (limit yok) - en kısa hazırlık süresi = dakikada daha çok vuruş. En iyisi tek hedef hasarı kahramanları + Signature Weapons'a geçmek, bu 30 dk içinde buff'ları kullanmak.",
    ru:"Своя rally: кто может запускать rally, лучше пусть запускает свою (без лимита) - кратчайшее время подготовки = больше ударов в минуту. Лучше всего перейти на героев одиночного урона + Signature Weapons, использовать баффы в эти 30 мин." } ],
  reservoir:[ { id:"res-anmelden", prio:true, tags:{de:["Anmelden","Wer ist dabei"],en:["Sign up","Who joins"],tr:["Kayıt","Kim katılıyor"],ru:["Запись","Кто участвует"]},
    de:"Anmelden: Jeder Platz zaehlt (30 gegen 30, letztes Mal nur 17 von 30). Event Reservoir Raid oeffnen, dann die Zeile unter dem eigenen Spielernamen, dann ANMELDEN oder ABMELDEN. Nur ANMELDEN, wenn du zu 100% dabei sein kannst - sonst bitte ABMELDEN, dann rueckt eine Reserve nach. Anmeldung schliesst rund 2 Tage vor Start.",
    en:"Sign up: every spot counts (30 vs 30, last time only 17 of 30). Open the event Reservoir Raid, then the line under your own player name, then SIGN UP or LEAVE. Only SIGN UP if you can be there 100% - otherwise please LEAVE, so a reserve can take the spot. Registration closes about 2 days before start.",
    tr:"Kayit: her yer onemli (30'a 30, gecen sefer sadece 17 / 30). Reservoir Raid etkinligini ac, sonra kendi oyuncu adinin altindaki satir, sonra SIGN UP veya LEAVE. Sadece %100 katilabileceksen SIGN UP - aksi halde lutfen LEAVE, boylece bir yedek yerini alir. Kayit baslamadan yaklasik 2 gun once kapanir.",
    ru:"Запись: каждое место важно (30 на 30, в прошлый раз только 17 из 30). Открой событие Reservoir Raid, затем строка под твоим именем игрока, затем SIGN UP или LEAVE. Нажимай SIGN UP только если можешь быть на 100% - иначе, пожалуйста, LEAVE, тогда резерв займёт место. Регистрация закрывается примерно за 2 дня до старта." },
  { id:"res-halten", prio:true, tags:{de:["Halten","Lineup"],en:["Hold","Lineup"],tr:["Tut","Dizilim"],ru:["Удержание","Расстановка"]},
    de:"Halten gewinnt, nicht Toeten: Hochwert-Gebaeude halten (Central Reservoir > grosse Komplexe > kleine Anlagen). Am besten nach Gebaeudewert aufstellen, die Staerksten aufs Central Reservoir. Lieber halten als nur Solo-Wasser jagen.",
    en:"Holding wins, not killing: hold high-value buildings (Central Reservoir > big complexes > small ones). Best to line up by value, the strongest on Central Reservoir. Better to hold than just chase solo water.",
    tr:"Öldürmek değil tutmak kazandırır: Yüksek değerli binaları tut (Central Reservoir > büyük kompleksler > küçük tesisler). En iyisi bina değerine göre dizilmek, en güçlüler Central Reservoir'da. Sadece tek başına su avlamak yerine tutmak daha iyi.",
    ru:"Удержание побеждает, а не убийство: удерживай ценные здания (Central Reservoir > большие комплексы > мелкие объекты). Лучше расставляться по ценности здания, сильнейшие на Central Reservoir. Лучше удерживать, чем просто гоняться за одиночной водой." },
  { id:"res-aufstellung", prio:false, tags:{de:["Aufstellung"],en:["Line-up"],tr:["Dizilim"],ru:["Расстановка"]},
    de:"Aufstellung je Phase und Gebäude: unten im Aufstellungs-Block eintragen (Anführer + Mitglieder), dann die fertigen Phasen-Nachrichten kopieren. Mitglieder sehen die Aufstellung auf der Reservoir-Raid-Eventseite.",
    en:"Line-up per phase and building: fill it in the line-up block below (leader + members), then copy the ready phase messages. Members see the line-up on the Reservoir Raid event page.",
    tr:"Faz ve bina başına dizilim: aşağıdaki dizilim bloğunda doldur (lider + üyeler), sonra hazır faz mesajlarını kopyala. Üyeler dizilimi Reservoir Raid etkinlik sayfasında görür.",
    ru:"Расстановка по фазам и зданиям: заполни в блоке расстановки ниже (лидер + участники), затем скопируй готовые сообщения по фазам. Участники видят расстановку на странице события Reservoir Raid." } ],
  stadt:[
    { id:"stadt-monster", prio:true, tags:{de:["Stadt + Monster","Nur kleine","Gross+mittel auf Ansage"],en:["City + monster","Small only","Big+mid on call"],tr:["Şehir + canavar","Sadece küçük","Büyük+orta çağrıyla"],ru:["Город + монстр","Только малые","Большой+средние по команде"]},
    de:"Stadt mit Monster: Lasst uns alle auf die KLEINEN gehen - jeder schickt 1 Trupp auf einen FREIEN kleinen, dann bekommt jeder Punkte. Das GROSSE (Zentrum) und die mittleren erst auf Ansage vom Commander. Ist das GROSSE nur noch bei 25 %, gehen wir alle gemeinsam aufs GROSSE. Wenn R4 ruft, kommt bitte zum Sammelpunkt.",
    en:"City with monster: let us all go for the SMALL ones - each sends 1 troop to a FREE small one, then everyone gets points. The BIG one (center) and the medium ones only on the commander's call. When the BIG one is at 25 %, we all go for it together. When R4 calls, please come to the rally point.",
    tr:"Canavarlı şehir: Hepimiz KÜÇÜK olanlara gidelim - herkes BOŞ bir küçüğe 1 birlik gönderir, böylece herkes puan alır. BÜYÜK olan (merkez) ve orta olanlar yalnızca Commander'ın çağrısıyla. BÜYÜK olan %25'e düştüğünde, hepimiz birlikte BÜYÜK olana gideriz. R4 çağırınca lütfen rally noktasına gelin.",
    ru:"Город с монстром: давайте все идём на МАЛЕНЬКИХ - каждый отправляет 1 отряд на СВОБОДНОГО маленького, тогда все получают очки. БОЛЬШОЙ (центр) и средних только по команде Commander. Когда у БОЛЬШОГО остаётся 25 %, идём на БОЛЬШОГО все вместе. Когда зовёт R4, пожалуйста, приходите на rally-точку." },
    { id:"stadt-allianz", prio:true, tags:{de:["Stadt + feindl. Allianz","Erobern + 30 Min halten"],en:["City + enemy alliance","Capture + hold 30 min"],tr:["Şehir + düşman ittifak","Ele geçir + 30 dk tut"],ru:["Город + вражеский альянс","Захват + удержать 30 мин"]},
    de:"Stadt mit feindlicher Allianz: Wir hauen gemeinsam drauf, bis die Stadt UNS gehoert, dann schicken alle ihre Truppen 30 Min zur Verteidigung rein - so bleibt sie unsere. Nur Ersteroberung gibt Sofortpunkte, Rueckeroberung nicht - dafuer lohnt sich kein Gem. Wenn R4 ruft, kommt bitte zum Sammelpunkt.",
    en:"City held by enemy alliance: we hit together until the city is OURS, then everyone sends their troops in for 30 min to defend - that keeps it ours. Only first capture gives instant points, recapture does not - no need to spend gems for it. When R4 calls, please come to the rally point.",
    tr:"Düşman ittifakının elindeki şehir: Şehir BİZİM olana kadar birlikte vururuz, sonra herkes savunma için 30 dk birliklerini içeri gönderir - böylece bizim kalır. Yalnızca ilk ele geçirme anında puan verir, geri alma vermez - bunun için Gem harcamaya değmez. R4 çağırınca lütfen rally noktasına gelin.",
    ru:"Город под контролем вражеского альянса: бьём вместе, пока город не станет НАШИМ, потом все отправляют войска на 30 мин в оборону - так он останется нашим. Только первый захват даёт мгновенные очки, повторный захват - нет, ради него не стоит тратить Gem. Когда зовёт R4, пожалуйста, приходите на rally-точку." }
  ],
  belagerung:[ { id:"bela-halten", prio:true, tags:{de:["Halten","Schild","Rollen"],en:["Hold","Shield","Roles"],tr:["Tut","Shield","Roller"],ru:["Удержание","Shield","Роли"]},
    de:"Arcadia + 4 Tuerme halten: T-50 gemeinsam versetzen, Rollen verteilen (Arcadia-Halter, Turm-Teams, Reaktion). 60 Sek Halten = 10.000 Punkte -> Dauerbesetzung schlaegt Kills. Schild-Disziplin; Hospital/Enlistment vorher leeren.",
    en:"Hold Arcadia + 4 towers: relocate together at T-50, assign roles (Arcadia holders, tower teams, reaction). 60 sec held = 10,000 points -> continuous occupation beats kills. Shield discipline; empty hospital/enlistment beforehand.",
    tr:"Arcadia + 4 kuleyi tut: T-50'de birlikte ışınlan, rolleri dağıt (Arcadia tutucular, kule ekipleri, reaksiyon). 60 sn tutmak = 10.000 puan -> sürekli işgal kill'leri yener. Shield disiplini; Hospital/Enlistment'ı önceden boşalt.",
    ru:"Удерживать Arcadia + 4 башни: телепортируемся вместе на T-50, распределяем роли (держатели Arcadia, команды башен, реакция). 60 сек удержания = 10 000 очков -> постоянное удержание сильнее киллов. Дисциплина Shield; заранее очистить Hospital/Enlistment." } ]
};

/* Event-Label + Emoji (gemeinsame Quelle fuer beide Seiten) */
var STRAT_EV={
  duell:{emo:"⚔️",name:{de:"Allianzduell",en:"Alliance Duel",tr:"Alliance Duel",ru:"Alliance Duel"}},
  loewe:{emo:"🦁",name:{de:"Ghulöwe",en:"Ghoulion",tr:"Ghoulion",ru:"Ghoulion"}},
  reservoir:{emo:"🐟",name:{de:"Reservoir Raid",en:"Reservoir Raid",tr:"Reservoir Raid",ru:"Reservoir Raid"}},
  stadt:{emo:"🌃",name:{de:"Stadtduell",en:"City Duel",tr:"City Duel",ru:"City Duel"}},
  belagerung:{emo:"👑",name:{de:"Allianzbelagerung",en:"Arcadian Conquest",tr:"Arcadian Conquest",ru:"Arcadian Conquest"}}
};

/* Tag-Labels je Sprache: x.tags kann Array (alt) ODER {de,en,tr,ru} sein. */
function stratTagArr(x,lang){ var t=x&&x.tags; if(!t) return []; if(Array.isArray(t)) return t; return t[lang]||t.en||t.de||[]; }
/* Strategie-Text je Sprache mit Fallback gewaehlt -> EN -> DE. */
function stratLoc(x,lang){ if(!x) return ""; return x[lang]!=null?x[lang]:(x.en!=null?x.en:(x.de!=null?x.de:"")); }
