/* ============ S1L Strategien je Event — GEMEINSAME QUELLE ============
   Einmal HIER pflegen -> Baukasten (S1L-R4-Raid.html) UND Timeline (S1L-R4-Templates.html)
   nutzen exakt dieselben Strategien. Auswahl-Labels (tags) je Sprache als {de,en,tr,ru}.
   Die GEWAEHLTE Strategie je Event wird live ueber Firebase-Collection 'stratchoice' geteilt.
   Format: warmer Einzeiler -> #080-Bullets -> optionale Stern-Bloecke (#<code> ***** TITEL ***** #<code>).
   Pflege: Alex. Einbinden: <script src="strat.js"></script> VOR dem Seiten-Skript. */
var STRAT={
  duell:[ { id:"duell-tag1", prio:false, tags:{de:["Tag 1 - Radar","Fetzen","Spionage"],en:["Day 1 - Radar","Scraps","Spy"],tr:["1. Gün - Radar","Scraps","Casus"],ru:["День 1 - Radar","Scraps","Шпион"]},
    de:"Lasst uns stark in die Woche starten!\n#080 AUSRUESTUNGSFETZEN verwenden - meiste Punkte (im Golden Window fuer 3 Events gleichzeitig)\n#080 SPIONAGEMISSIONEN machen - viele Punkte (kosten Ausdauer)\n#080 Nahrung, Holz, Metall, Benzin sammeln\n———\n#189 ***** AUFHEBEN ***** #189\n#080 Fuer TAG 2: Bau-Speedups\n#080 Fuer TAG 3: Forschungs-Speedups + Ungeheuer-Zellen + Ungeheuer-Serum",
    en:"Let us start the week strong!\n#080 USE GEAR SCRAPS - most points (for 3 events at once in the Golden Window)\n#080 RUN SPY MISSIONS - high points (cost stamina)\n#080 Gather food, wood, metal, fuel\n———\n#189 ***** SAVE ***** #189\n#080 For DAY 2: build speedups\n#080 For DAY 3: research speedups + Behemoth Cells + Behemoth Serum",
    tr:"Haftaya guclu baslayalim!\n#080 GEAR SCRAPS KULLAN - en cok puan (Golden Window'da ayni anda 3 etkinlik icin)\n#080 CASUS GOREVLERI yap - cok puan (dayaniklilik harcar)\n#080 Yiyecek, odun, metal, yakit topla\n———\n#189 ***** SAKLA ***** #189\n#080 2. GUN icin: build speedups\n#080 3. GUN icin: research speedups + Behemoth Cells + Behemoth Serum",
    ru:"Начнём неделю сильно!\n#080 ИСПОЛЬЗУЙ GEAR SCRAPS - больше всего очков (в Golden Window сразу для 3 событий)\n#080 ДЕЛАЙ SPY-МИССИИ - много очков (тратят выносливость)\n#080 Собирай еду, дерево, металл, топливо\n———\n#189 ***** КОПИ ***** #189\n#080 На ДЕНЬ 2: build speedups\n#080 На ДЕНЬ 3: research speedups + Behemoth Cells + Behemoth Serum" },
  { id:"duell-tag2", prio:false, tags:{de:["Tag 2 - Basisbau","Bau-Speedups","Golden Window"],en:["Day 2 - Base Building","Build speedups","Golden Window"],tr:["2. Gün - Base Building","Build speedups","Golden Window"],ru:["День 2 - Base Building","Build speedups","Golden Window"]},
    de:"Heute zaehlt BAUEN - lasst uns gemeinsam stark bauen!\n#080 BAU-SPEEDUPS im Golden Window dumpen - zaehlt dreifach\n#080 S-Stufe (+75.000) und LKW (+50.000) als Extra mitnehmen\n#080 Bau-Speedups vorher NICHT einzeln verbrauchen\n———\n#189 ***** AUFHEBEN ***** #189\n#080 Fuer TAG 3: Forschungs-Speedups + Ungeheuer-Zellen + Ungeheuer-Serum + Kampfmedaillen\n#080 Fuer TAG 4: Heldenfragmente + Rekrutierungsmarken",
    en:"Today it is all about BUILDING - let us build strong together!\n#080 Dump BUILD SPEEDUPS in the Golden Window - counts triple\n#080 S-tier (+75,000) and truck (+50,000) as extras\n#080 Do NOT spend build speedups one by one before\n———\n#189 ***** SAVE ***** #189\n#080 For DAY 3: research speedups + Behemoth Cells + Behemoth Serum + Battle Medals\n#080 For DAY 4: hero fragments + recruit tokens",
    tr:"Bugun is INSAAT - birlikte guclu insa edelim!\n#080 BUILD SPEEDUPS'i Golden Window'da harca - uc kat sayilir\n#080 S-tier (+75.000) ve truck (+50.000) ekstra\n#080 Build speedups'i oncesinde tek tek HARCAMA\n———\n#189 ***** SAKLA ***** #189\n#080 3. GUN icin: research speedups + Behemoth Cells + Behemoth Serum + Battle Medal\n#080 4. GUN icin: hero parcalari + rekrutasyon marka",
    ru:"Сегодня главное - СТРОЙКА - построим сильно вместе!\n#080 Слей BUILD SPEEDUPS в Golden Window - втрое\n#080 S-tier (+75.000) и грузовик (+50.000) как бонус\n#080 НЕ трать build speedups по одному заранее\n———\n#189 ***** КОПИ ***** #189\n#080 На ДЕНЬ 3: research speedups + Behemoth Cells + Behemoth Serum + Battle Medals\n#080 На ДЕНЬ 4: фрагменты героев + жетоны вербовки" },
  { id:"duell-tag3", prio:false, tags:{de:["Tag 3 - Technologie","Forschungs-Speedups","Ungeheuer"],en:["Day 3 - Technology","Research speedups","Behemoth"],tr:["3. Gün - Technology","Research speedups","Behemoth"],ru:["День 3 - Technology","Research speedups","Behemoth"]},
    de:"Heute Forschung - jeder Beitrag zaehlt!\n#080 FORSCHUNGS-SPEEDUPS im Golden Window dumpen - zaehlt dreifach\n#080 Ungeheuer-Zellen (+12.000), Spionagemission (+30.000), Kampfmedaille ausgeben (+2.500)\n———\n#189 ***** AUFHEBEN ***** #189\n#080 Fuer TAG 4: Heldenfragmente + Rekrutierungsmarken\n#080 Fuer TAG 5: Spionage + Ressourcen fuers Truppen-Training",
    en:"Today is research - every bit counts!\n#080 Dump RESEARCH SPEEDUPS in the Golden Window - counts triple\n#080 Behemoth Cells (+12,000), spy mission (+30,000), spend Battle Medal (+2,500)\n———\n#189 ***** SAVE ***** #189\n#080 For DAY 4: hero fragments + recruit tokens\n#080 For DAY 5: spy + resources for troop training",
    tr:"Bugun arastirma - her katki onemli!\n#080 RESEARCH SPEEDUPS'i Golden Window'da harca - uc kat sayilir\n#080 Behemoth Cells (+12.000), casus gorevi (+30.000), Battle Medal harca (+2.500)\n———\n#189 ***** SAKLA ***** #189\n#080 4. GUN icin: hero parcalari + rekrutasyon marka\n#080 5. GUN icin: casus + birlik egitimi icin kaynaklar",
    ru:"Сегодня исследования - важен каждый вклад!\n#080 Слей RESEARCH SPEEDUPS в Golden Window - втрое\n#080 Behemoth Cells (+12.000), spy-миссия (+30.000), потратить Battle Medal (+2.500)\n———\n#189 ***** КОПИ ***** #189\n#080 На ДЕНЬ 4: фрагменты героев + жетоны вербовки\n#080 На ДЕНЬ 5: spy + ресурсы для тренировки войск" },
  { id:"duell-tag4", prio:true, tags:{de:["Tag 4 - Helden","Fragmente","Alpha-Bestie"],en:["Day 4 - Heroes","Fragments","Alpha Beast"],tr:["4. Gün - Heroes","Parçalar","Alpha Beast"],ru:["День 4 - Heroes","Фрагменты","Alpha Beast"]},
    de:"Heute Helden - lasst uns gemeinsam stark werden!\n#080 HELDENFRAGMENTE einsetzen - legendaere + Wunsch-Rekrutierung am staerksten (im Golden Window dreifach)\n#080 Fragmente farmen: Rallys auf die MITTLEREN Monster (Alpha-Bestie) - normale/fette Infizierte geben keine\n———\n#189 ***** AUFHEBEN ***** #189\n#080 Fuer TAG 5: Spionage + Trainings-Speedups + Ressourcen fuers Training\n#080 Fuer TAG 6: Friedenskuppeln + alle Beschleuniger",
    en:"Today heroes - let us grow strong together!\n#080 USE HERO FRAGMENTS - legendary + wish recruitment strongest (triple in the Golden Window)\n#080 Farm fragments: rallies on the MEDIUM monsters (Alpha Beast) - normal/fat infected give none\n———\n#189 ***** SAVE ***** #189\n#080 For DAY 5: spy + training speedups + resources for training\n#080 For DAY 6: Peace Shields + all speedups",
    tr:"Bugun kahramanlar - birlikte guclenelim!\n#080 HERO FRAGMENTS kullan - efsanevi + istek rekrutasyonu en guclu (Golden Window'da uc kat)\n#080 Parca farmla: ORTA canavarlara (Alpha Beast) rally - normal/sisman enfekteler vermez\n———\n#189 ***** SAKLA ***** #189\n#080 5. GUN icin: casus + training speedups + egitim icin kaynaklar\n#080 6. GUN icin: Peace Shields + tum speedups",
    ru:"Сегодня герои - станем сильнее вместе!\n#080 ИСПОЛЬЗУЙ HERO FRAGMENTS - легендарные + желаемая вербовка сильнее всего (в Golden Window втрое)\n#080 Фарм фрагментов: rally на СРЕДНИХ монстров (Alpha Beast) - обычные/толстые заражённые не дают\n———\n#189 ***** КОПИ ***** #189\n#080 На ДЕНЬ 5: spy + training speedups + ресурсы для тренировки\n#080 На ДЕНЬ 6: Peace Shields + все speedups" },
  { id:"duell-tag5", prio:false, tags:{de:["Tag 5 - Schlachtvorbereitung","Spionage","Training"],en:["Day 5 - Battle Prep","Spy","Training"],tr:["5. Gün - Battle Prep","Casus","Eğitim"],ru:["День 5 - Battle Prep","Шпион","Тренировка"]},
    de:"Heute Schlachtvorbereitung - ihr macht das super!\n#080 SPIONAGEMISSION (+37.500) + Truppen trainieren (hoehere Stufen mehr Punkte)\n#080 Training braucht Ressourcen - genug bereithalten (Truppen hat man genug)\n#080 Heute KEIN Golden Window (keine Power-Play-Truppen-Runde)\n———\n#189 ***** AUFHEBEN ***** #189\n#080 Fuer TAG 6: Friedenskuppeln + alle Beschleuniger\n#080 Fuer MONTAG (Tag 1): Ausruestungsfetzen + Spionage + Kommandantenausdauer (Sonntag ist duellfrei)",
    en:"Today battle prep - you are doing great!\n#080 SPY MISSION (+37,500) + train troops (higher tiers more points)\n#080 Training needs resources - keep enough ready (you have enough troops)\n#080 NO Golden Window today (no Power Play troop round)\n———\n#189 ***** SAVE ***** #189\n#080 For DAY 6: Peace Shields + all speedups\n#080 For MONDAY (Day 1): gear scraps + spy + commander stamina (Sunday has no duel)",
    tr:"Bugun savas hazirligi - harika gidiyorsunuz!\n#080 CASUS GOREVI (+37.500) + birlik egit (ust seviyeler daha cok puan)\n#080 Egitim kaynak ister - yeterince hazir tut (birlik yeterli)\n#080 Bugun Golden Window YOK (Power Play birlik turu yok)\n———\n#189 ***** SAKLA ***** #189\n#080 6. GUN icin: Peace Shields + tum speedups\n#080 PAZARTESI icin (1. Gun): gear scraps + casus + komutan dayanikligi (Pazar duel yok)",
    ru:"Сегодня подготовка к бою - вы молодцы!\n#080 SPY-МИССИЯ (+37.500) + тренировать войска (выше уровень - больше очков)\n#080 Тренировка требует ресурсов - держи запас (войск хватает)\n#080 Сегодня НЕТ Golden Window (нет раунда войск в Power Play)\n———\n#189 ***** КОПИ ***** #189\n#080 На ДЕНЬ 6: Peace Shields + все speedups\n#080 На ПОНЕДЕЛЬНИК (День 1): gear scraps + spy + выносливость командира (в воскресенье дуэли нет)" },
  { id:"duell-tag6-kuppel", prio:true, tags:{de:["Tag 6 - Alle unter die Kuppel","Verteidigen","Verstaerken"],en:["Day 6 - Everyone under the dome","Defend","Reinforce"],tr:["6. Gun - Herkes dome altina","Savun","Takviye"],ru:["День 6 - Все под купол","Защита","Усиление"]},
    de:"TAG 6 - bitte alle UNTER DIE KUPPEL, gemeinsam halten wir stand!\n#080 Unter der Kuppel seid ihr unangreifbar\n#080 Wer angreift, verliert die Kuppel (30 Min Abklingzeit)\n#080 Trupps DRAUSSEN sind angreifbar - bei Angriffen zurueckrufen\n———\n#078 ***** VERSTAERKEN ***** #078\n#080 Siedlungen OHNE Kuppel mit der STAERKSTEN Truppe verstaerken (bis 5 Plaetze)\n#080 Gewinnt der Verteidiger, zaehlt der Kill fuer UNS\n———\n#080 Hebel: Sandwurm-Eier (perfekt +500.000), S-Aufgabe, LKW, Beschleuniger\n#080 VOR jedem Angriff im Chat fragen - wir stimmen uns ab",
    en:"DAY 6 - everyone UNDER THE DOME please, together we hold!\n#080 Under the dome you cannot be attacked\n#080 Whoever attacks loses the dome (30 min cooldown)\n#080 Troops OUTSIDE can be attacked - recall them when attacks come\n———\n#078 ***** REINFORCE ***** #078\n#080 Reinforce settlements WITHOUT a dome with your STRONGEST troops (up to 5)\n#080 If the defender wins, the kill counts for US\n———\n#080 Levers: sandworm eggs (perfect +500,000), S-task, truck, speedups\n#080 ASK in chat before every attack - we coordinate",
    tr:"6. GUN - lutfen herkes DOME ALTINA, birlikte dayaniriz!\n#080 Dome altinda saldirilmaz olursunuz\n#080 Saldiran dome'u kaybeder (30 dk bekleme)\n#080 DISARIDAKI birlikler saldirilabilir - saldirilarda geri cagir\n———\n#078 ***** TAKVIYE ***** #078\n#080 Dome'suz yerlesimleri EN GUCLU birlikle takviye et (5'e kadar)\n#080 Savunan kazanirsa kill BIZE sayilir\n———\n#080 Kaldiraclar: kum solucani yumurtalari (mukemmel +500.000), S-gorev, kamyon, speedups\n#080 Her saldiridan ONCE chat'te sor - uyum saglayalim",
    ru:"ДЕНЬ 6 - все ПОД КУПОЛ, пожалуйста, вместе выстоим!\n#080 Под куполом вас нельзя атаковать\n#080 Кто атакует, теряет купол (30 мин перезарядка)\n#080 Войска СНАРУЖИ можно атаковать - отзывайте при атаках\n———\n#078 ***** УСИЛЕНИЕ ***** #078\n#080 Усиливайте поселения БЕЗ купола САМЫМИ сильными войсками (до 5)\n#080 Если защитник побеждает, килл засчитывается НАМ\n———\n#080 Рычаги: яйца песчаного червя (идеальное +500.000), S-задача, грузовик, speedups\n#080 СПРАШИВАЙТЕ в чате перед каждой атакой - согласуем" },
  { id:"duell-tag6-v1", prio:false, tags:{de:["Tag 6 V1 (?)","Rotation","Kuppel"],en:["Day 6 V1 (?)","Rotation","Dome"],tr:["6. Gün V1 (?)","Rotasyon","Dome"],ru:["День 6 V1 (?)","Ротация","Купол"]},
    de:"TAG 6 V1 (in Abstimmung) - feste 6er-Teams mit Rotation:\n#080 Vorm Schlafen Kuppel AN\n#080 Immer 1 greift OHNE Kuppel an, die anderen 5 verstaerken/verteidigen\n#080 Bei Gegenschaden zurueck, dann rotieren (Naechster ohne Kuppel, Voriger Kuppel wieder hoch)\n#080 Gegner ueber 3 Stufen unter dir = KEINE Punkte - nicht angreifen",
    en:"DAY 6 V1 (under discussion) - fixed teams of 6 with rotation:\n#080 Dome ON before sleeping\n#080 Always 1 attacks WITHOUT a dome, the other 5 reinforce/defend\n#080 On counter-damage retreat, then rotate (next without dome, previous raises dome again)\n#080 Enemies more than 3 levels below you = NO points - do not attack",
    tr:"6. GUN V1 (gorusuluyor) - rotasyonlu sabit 6'li takimlar:\n#080 Yatmadan once dome ACIK\n#080 Her zaman 1 dome OLMADAN saldirir, diger 5 takviye/savunma\n#080 Karsi hasarda geri, sonra rotasyon (siradaki dome'suz, onceki dome'u tekrar acar)\n#080 Senden 3 seviyeden fazla dusuk dusman = PUAN YOK - saldirma",
    ru:"ДЕНЬ 6 V1 (обсуждается) - фиксированные группы по 6 с ротацией:\n#080 Купол ВКЛ перед сном\n#080 Всегда 1 атакует БЕЗ купола, остальные 5 усиливают/защищают\n#080 При ответном уроне назад, затем ротация (следующий без купола, предыдущий снова поднимает купол)\n#080 Враги более чем на 3 уровня ниже = НЕТ очков - не атаковать" },
  { id:"duell-tag6-v2", prio:false, tags:{de:["Tag 6 V2 (?)","Dauerverteidiger","Kuppel"],en:["Day 6 V2 (?)","Permanent defender","Dome"],tr:["6. Gün V2 (?)","Kalıcı savunucu","Dome"],ru:["День 6 V2 (?)","Защитник","Купол"]},
    de:"TAG 6 V2 (in Abstimmung) - Dauerverteidiger ohne Kuppel:\n#080 Ein eh-online Spieler bleibt GANZ OHNE Kuppel, voll verstaerkt\n#080 Verteidigt am Stuetzpunkt jeden ankommenden Fremden\n#080 Bei Gefahr sofort Kuppel an (Abklingzeit laengst vorbei)\n#080 Starke schicken ihm Truppen + beobachten die Statistik (rechtzeitig fliehen, verstecken)",
    en:"DAY 6 V2 (under discussion) - permanent defender without a dome:\n#080 A player who is online anyway stays WITHOUT a dome, fully reinforced\n#080 Defends every incoming enemy at the base\n#080 On danger turn the dome on instantly (cooldown long over)\n#080 The strong send him troops + watch the stats (flee in time, hide)",
    tr:"6. GUN V2 (gorusuluyor) - dome'suz kalici savunucu:\n#080 Zaten online olan bir oyuncu DOME'SUZ kalir, tam takviyeli\n#080 Uste gelen her dusmani savunur\n#080 Tehlikede dome'u aninda acar (bekleme coktan bitti)\n#080 Gucluler ona birlik gonderir + istatistigi izler (zamaninda kac, saklan)",
    ru:"ДЕНЬ 6 V2 (обсуждается) - постоянный защитник без купола:\n#080 Игрок, который и так онлайн, остаётся БЕЗ купола, полностью усилен\n#080 Защищает на базе каждого входящего врага\n#080 При опасности сразу включает купол (перезарядка давно прошла)\n#080 Сильные шлют ему войска + следят за статистикой (вовремя бежать, прятаться)" } ],
  loewe:[ { id:"loewe-selbst", prio:true, tags:{de:["Boss","Schaden"],en:["Boss","Damage"],tr:["Boss","Hasar"],ru:["Босс","Урон"]},
    de:"Ghuloewe - jeder Schlag zaehlt, danke fuers Mitmachen!\n#080 Wer rally-faehig ist, startet am besten eine EIGENE Rally (kein Limit)\n#080 Kuerzeste Vorlaufzeit = mehr Schlaege pro Minute\n#080 Auf Boss-Schaden-Helden + Signature Weapons umruesten\n#080 Buffs in diesen 30 Min einsetzen",
    en:"Ghoulion - every hit counts, thanks for joining!\n#080 If you can rally, best start your OWN rally (no limit)\n#080 Shortest lead time = more hits per minute\n#080 Switch to single-target heroes + signature weapons\n#080 Use buffs in these 30 min",
    tr:"Ghoulion - her vurus onemli, katildiginiz icin tesekkurler!\n#080 Rally baslatabilen en iyisi KENDI rally'sini baslatsin (limit yok)\n#080 En kisa hazirlik suresi = dakikada daha cok vurus\n#080 Tek hedef hasari kahramanlari + Signature Weapons'a gec\n#080 Bu 30 dk icinde buff'lari kullan",
    ru:"Ghoulion - важен каждый удар, спасибо за участие!\n#080 Кто может rally, лучше запусти СВОЮ rally (без лимита)\n#080 Кратчайшее время подготовки = больше ударов в минуту\n#080 Перейди на героев одиночного урона + Signature Weapons\n#080 Используй баффы в эти 30 мин" } ],
  reservoir:[ { id:"res-anmelden", prio:true, tags:{de:["Anmelden","Wer ist dabei"],en:["Sign up","Who joins"],tr:["Kayıt","Kim katılıyor"],ru:["Запись","Кто участвует"]},
    de:"Reservoir Raid - jeder Platz zaehlt, kommt zahlreich!\n#080 30 gegen 30 - letztes Mal nur 17 von 30\n#080 Event oeffnen, Zeile unter deinem Namen, dann ANMELDEN oder ABMELDEN\n#080 Nur ANMELDEN, wenn du zu 100% dabei sein kannst\n#080 Sonst bitte ABMELDEN, dann rueckt eine Reserve nach\n#080 Anmeldung schliesst rund 2 Tage vor Start",
    en:"Reservoir Raid - every spot counts, come in numbers!\n#080 30 vs 30 - last time only 17 of 30\n#080 Open the event, line under your name, then SIGN UP or LEAVE\n#080 Only SIGN UP if you can be there 100%\n#080 Otherwise please LEAVE, so a reserve can take the spot\n#080 Registration closes about 2 days before start",
    tr:"Reservoir Raid - her yer onemli, cok sayida gelin!\n#080 30'a 30 - gecen sefer sadece 17 / 30\n#080 Etkinligi ac, adinin altindaki satir, sonra SIGN UP veya LEAVE\n#080 Sadece %100 katilabileceksen SIGN UP\n#080 Aksi halde lutfen LEAVE, yedek yerini alir\n#080 Kayit baslamadan ~2 gun once kapanir",
    ru:"Reservoir Raid - важно каждое место, приходите все!\n#080 30 на 30 - в прошлый раз только 17 из 30\n#080 Открой событие, строка под именем, затем SIGN UP или LEAVE\n#080 SIGN UP только если можешь на 100%\n#080 Иначе, пожалуйста, LEAVE, резерв займёт место\n#080 Регистрация закрывается ~2 дня до старта" },
  { id:"res-halten", prio:true, tags:{de:["Halten","Lineup"],en:["Hold","Lineup"],tr:["Tut","Dizilim"],ru:["Удержание","Расстановка"]},
    de:"Reservoir - Halten gewinnt, nicht Toeten!\n#080 Hochwert-Gebaeude halten (Central Reservoir > grosse Komplexe > kleine)\n#080 Nach Gebaeudewert aufstellen, die Staerksten aufs Central Reservoir\n#080 Lieber halten als nur Solo-Wasser jagen",
    en:"Reservoir - holding wins, not killing!\n#080 Hold high-value buildings (Central Reservoir > big complexes > small)\n#080 Line up by value, the strongest on Central Reservoir\n#080 Better to hold than chase solo water",
    tr:"Reservoir - tutmak kazandirir, oldurmek degil!\n#080 Yuksek degerli binalari tut (Central Reservoir > buyuk kompleksler > kucuk)\n#080 Bina degerine gore diziL, en gucluler Central Reservoir'da\n#080 Tek basina su avlamaktansa tutmak daha iyi",
    ru:"Reservoir - удержание побеждает, а не убийство!\n#080 Удерживай ценные здания (Central Reservoir > большие комплексы > мелкие)\n#080 Расставляйся по ценности, сильнейшие на Central Reservoir\n#080 Лучше удерживать, чем гоняться за одиночной водой" },
  { id:"res-aufstellung", prio:false, tags:{de:["Aufstellung"],en:["Line-up"],tr:["Dizilim"],ru:["Расстановка"]},
    de:"Reservoir - Aufstellung je Phase und Gebaeude:\n#080 Unten im Aufstellungs-Block eintragen (Anfuehrer + Mitglieder)\n#080 Dann die fertigen Phasen-Nachrichten kopieren\n#080 Mitglieder sehen die Aufstellung auf der Reservoir-Raid-Eventseite",
    en:"Reservoir - line-up per phase and building:\n#080 Fill it in the line-up block below (leader + members)\n#080 Then copy the ready phase messages\n#080 Members see the line-up on the Reservoir Raid event page",
    tr:"Reservoir - faz ve bina basina dizilim:\n#080 Asagidaki dizilim blogunda doldur (lider + uyeler)\n#080 Sonra hazir faz mesajlarini kopyala\n#080 Uyeler dizilimi Reservoir Raid etkinlik sayfasinda gorur",
    ru:"Reservoir - расстановка по фазам и зданиям:\n#080 Заполни в блоке расстановки ниже (лидер + участники)\n#080 Затем скопируй готовые сообщения по фазам\n#080 Участники видят расстановку на странице события Reservoir Raid" } ],
  stadt:[
    { id:"stadt-monster", prio:true, tags:{de:["Stadt + Monster","Nur kleine","Gross+mittel auf Ansage"],en:["City + monster","Small only","Big+mid on call"],tr:["Şehir + canavar","Sadece küçük","Büyük+orta çağrıyla"],ru:["Город + монстр","Только малые","Большой+средние по команде"]},
    de:"Stadtduell mit Monster - lasst uns alle auf die KLEINEN!\n#080 Jeder schickt 1 Trupp auf einen FREIEN kleinen - so bekommt jeder Punkte\n#080 Das GROSSE (Zentrum) und die mittleren erst auf Ansage vom Commander\n#080 Ist das GROSSE nur noch bei 25%, gehen wir alle gemeinsam drauf\n#080 Wenn R4 ruft, kommt bitte zum Sammelpunkt",
    en:"City duel with monster - let us all go for the SMALL ones!\n#080 Each sends 1 troop to a FREE small one - so everyone gets points\n#080 The BIG one (center) and the medium ones only on the commander's call\n#080 When the BIG one is at 25%, we all go for it together\n#080 When R4 calls, please come to the rally point",
    tr:"Canavarli sehir duellosu - hepimiz KUCUK olanlara!\n#080 Herkes BOS bir kucuge 1 birlik gonderir - boylece herkes puan alir\n#080 BUYUK olan (merkez) ve ortalar yalnizca Commander cagrisiyla\n#080 BUYUK olan %25'e dusunce hepimiz birlikte gideriz\n#080 R4 cagirinca lutfen rally noktasina gelin",
    ru:"Городской дуэль с монстром - все идём на МАЛЕНЬКИХ!\n#080 Каждый шлёт 1 отряд на СВОБОДНОГО маленького - тогда все получают очки\n#080 БОЛЬШОЙ (центр) и средних только по команде Commander\n#080 Когда у БОЛЬШОГО 25%, идём на него все вместе\n#080 Когда зовёт R4, приходите на точку сбора" },
    { id:"stadt-allianz", prio:true, tags:{de:["Stadt + feindl. Allianz","Erobern + 30 Min halten"],en:["City + enemy alliance","Capture + hold 30 min"],tr:["Şehir + düşman ittifak","Ele geçir + 30 dk tut"],ru:["Город + вражеский альянс","Захват + удержать 30 мин"]},
    de:"Stadtduell mit feindlicher Allianz - gemeinsam drauf!\n#080 Wir hauen zusammen drauf, bis die Stadt UNS gehoert\n#080 Dann alle Truppen 30 Min zur Verteidigung reinschicken - so bleibt sie unsere\n#080 Nur Ersteroberung gibt Sofortpunkte, Rueckeroberung nicht - kein Gem dafuer\n#080 Wenn R4 ruft, kommt bitte zum Sammelpunkt",
    en:"City duel vs enemy alliance - hit it together!\n#080 We hit together until the city is OURS\n#080 Then everyone sends troops in for 30 min to defend - that keeps it ours\n#080 Only first capture gives instant points, recapture does not - no gems for it\n#080 When R4 calls, please come to the rally point",
    tr:"Dusman ittifakli sehir duellosu - birlikte vuralim!\n#080 Sehir BIZIM olana kadar birlikte vururuz\n#080 Sonra herkes 30 dk savunma icin birlik gonderir - boylece bizim kalir\n#080 Yalnizca ilk ele gecirme aninda puan verir, geri alma vermez - Gem harcamayin\n#080 R4 cagirinca lutfen rally noktasina gelin",
    ru:"Городской дуэль против вражеского альянса - бьём вместе!\n#080 Бьём вместе, пока город не станет НАШИМ\n#080 Потом все шлют войска на 30 мин в оборону - так останется нашим\n#080 Только первый захват даёт мгновенные очки, повторный - нет, не тратьте Gem\n#080 Когда зовёт R4, приходите на точку сбора" }
  ],
  belagerung:[ { id:"bela-halten", prio:true, tags:{de:["Halten","Schild","Rollen"],en:["Hold","Shield","Roles"],tr:["Tut","Shield","Roller"],ru:["Удержание","Shield","Роли"]},
    de:"Allianzbelagerung - Arcadia + 4 Tuerme halten, gemeinsam stark!\n#080 T-50 gemeinsam versetzen, Rollen verteilen (Arcadia-Halter, Turm-Teams, Reaktion)\n#080 60 Sek Halten = 10.000 Punkte - Dauerbesetzung schlaegt Kills\n#080 Schild-Disziplin; Hospital/Enlistment vorher leeren",
    en:"Arcadian Conquest - hold Arcadia + 4 towers, strong together!\n#080 Relocate together at T-50, assign roles (Arcadia holders, tower teams, reaction)\n#080 60 sec held = 10,000 points - continuous occupation beats kills\n#080 Shield discipline; empty hospital/enlistment beforehand",
    tr:"Arcadian Conquest - Arcadia + 4 kuleyi tut, birlikte gucluyuz!\n#080 T-50'de birlikte isinlan, rolleri dagit (Arcadia tutucular, kule ekipleri, reaksiyon)\n#080 60 sn tutmak = 10.000 puan - surekli isgal kill'leri yener\n#080 Shield disiplini; Hospital/Enlistment'i onceden bosalt",
    ru:"Arcadian Conquest - удерживай Arcadia + 4 башни, вместе сильны!\n#080 Телепорт вместе на T-50, распределите роли (держатели Arcadia, команды башен, реакция)\n#080 60 сек удержания = 10.000 очков - постоянное удержание сильнее киллов\n#080 Дисциплина Shield; заранее очистить Hospital/Enlistment" } ]
};

/* Event-Label + Emoji (gemeinsame Quelle fuer beide Seiten) */
var STRAT_EV={
  duell:{emo:"⚔️",name:{de:"Allianzduell",en:"Alliance Duel",tr:"Alliance Duel",ru:"Alliance Duel"}},
  loewe:{emo:"🦁",name:{de:"Ghulöwe",en:"Ghoulion",tr:"Ghoulion",ru:"Ghoulion"}},
  reservoir:{emo:"🐟",name:{de:"Reservoir Raid",en:"Reservoir Raid",tr:"Reservoir Raid",ru:"Reservoir Raid"}},
  stadt:{emo:"🌃",name:{de:"Stadtduell",en:"City Duel",tr:"City Duel",ru:"City Duel"}},
  belagerung:{emo:"👑",name:{de:"Allianzbelagerung",en:"Arcadian Conquest",tr:"Arcadian Conquest",ru:"Arcadian Conquest"}}
};

/* Tag-Labels je Sprache: x.tags kann Array (alt) ODER {de,en,tr,ru} sein. */
function stratTagArr(x,lang){ var t=x&&x.tags; if(!t) return []; if(Array.isArray(t)) return t; return t[lang]||t.en||t.de||[]; }
/* Strategie-Text je Sprache mit Fallback gewaehlt -> EN -> DE. */
function stratLoc(x,lang){ if(!x) return ""; return x[lang]!=null?x[lang]:(x.en!=null?x.en:(x.de!=null?x.de:"")); }
